### ISSUE TITLE
photoaerienne ancienne

### ISSUE THREAD

**Issue by ClaireCrassousPNM** [PnMercantour/suivi_zh#24]
va voir Elina qui a testé plusieurs couches qu'on pourrait mettre en fond (au choix) pour voir comment les ZH ont pu évoluer jusqu'à maintenant !

**Comment by ClaireCrassousPNM** [comment]
J'ai regardé sur https://remonterletemps.ign.fr/telecharger?x=7.395829&y=44.055390&z=10&layer=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&demat=DEMAT.PVA$GEOPORTAIL:DEMAT;PHOTOS&missionId=missions.6496046
A priori tout le territoire du Parc a été survolé dans les années 1954 1955. Donc à voir si tu arrives à trouver comment faire afficher la première couche 1950-1965 ?

**Comment by vprunet** [comment]
le commit f362fac permet l'affichage des orthophotos historiques.
